# -*- coding: utf-8 -*-
"""clase_metricas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fm0oSy0q30uVGUO6fyH_HsMF2SJLhdGD
"""

# ===========================================
# MÉTRICAS DE DESEMPEÑO EN INVERSIÓN
# Sharpe, Sortino, Treynor, Information Ratio, Calmar
# ===========================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

# -------------------------------------------
# 1. Descarga de datos
# -------------------------------------------
tickers = ["AAPL", "^GSPC"]  # AAPL = Apple; ^GSPC = índice S&P500 (benchmark)
data = yf.download(tickers, start="2019-01-01", end="2021-01-01")["Close"]

# Calcular retornos diarios porcentuales
returns = data.pct_change().dropna()
returns.columns = ["AAPL", "SP500"]

# -------------------------------------------
# 2. Parámetros base
# -------------------------------------------
rf = 0.045  # tasa libre de riesgo anual (4.5%)
periods_per_year = 252  # número típico de días de trading en un año
rf_daily = (1 + rf)**(1/periods_per_year) - 1  # tasa libre de riesgo diaria

# -------------------------------------------
# 3. Sharpe Ratio
# -------------------------------------------
def sharpe_ratio(r, rf_rate=rf_daily, periods=252):
    """
    r: Serie de retornos del activo o portafolio
    rf_rate: tasa libre de riesgo (por periodo)
    periods: número de periodos en un año (252 = diario)
    """
    excess = r - rf_rate             # retornos en exceso = R_p - R_f
    mean_excess = np.mean(excess)    # E[R_p - R_f]
    std_excess = np.std(excess)      # desviación estándar σ(R_p - R_f)
    sharpe = np.sqrt(periods) * mean_excess / std_excess
    return sharpe

# -------------------------------------------
# 4. Sortino Ratio
# -------------------------------------------
def sortino_ratio(r, rf_rate=rf_daily, target=0, periods=252):
    """
    r: retornos del portafolio
    rf_rate: tasa libre de riesgo
    target: retorno mínimo aceptable (T)
    """
    excess = r - rf_rate                  # retornos sobre libre de riesgo
    downside = r[r < target] - target     # solo pérdidas respecto al objetivo
    downside_std = np.sqrt(np.mean(downside**2))  # desviación a la baja σ_d
    mean_excess = np.mean(excess)
    sortino = np.sqrt(periods) * mean_excess / downside_std
    return sortino

# -------------------------------------------
# 5. Treynor Ratio
# -------------------------------------------
def treynor_ratio(r, benchmark, rf_rate=rf_daily, periods=252):
    """
    r: retornos del portafolio
    benchmark: retornos del índice de referencia (p.ej. S&P500)
    rf_rate: tasa libre de riesgo
    """
    excess_r = r - rf_rate           # exceso del portafolio
    excess_b = benchmark - rf_rate   # exceso del benchmark
    beta = np.cov(excess_r, excess_b)[0,1] / np.var(excess_b)  # covarianza / varianza
    treynor = np.mean(excess_r) * periods / beta
    return treynor

# -------------------------------------------
# 6. Information Ratio (IR)
# -------------------------------------------
def information_ratio(r, benchmark, periods=252):
    """
    r: retornos del portafolio
    benchmark: retornos del índice de referencia
    """
    active = r - benchmark           # diferencia activa (alpha)
    ir = np.sqrt(periods) * np.mean(active) / np.std(active)  # media / volatilidad del tracking error
    return ir

# -------------------------------------------
# 7. Calmar Ratio
# -------------------------------------------
def calmar_ratio(r, periods=252):
    """
    r: retornos del portafolio
    """
    cumulative = (1 + r).cumprod()           # curva de capital
    running_max = cumulative.cummax()        # máximo acumulado
    drawdown = (cumulative - running_max) / running_max
    max_dd = abs(drawdown.min())             # máxima caída (máx. drawdown)
    cagr = (cumulative[-1])**(periods / len(r)) - 1  # tasa compuesta anual (CAGR)
    calmar = cagr / max_dd
    return calmar

# -------------------------------------------
# 8. Aplicación de las métricas a Apple
# -------------------------------------------
aapl = returns["AAPL"]
sp500 = returns["SP500"]

metrics = {
    "Sharpe": sharpe_ratio(aapl),
    "Sortino": sortino_ratio(aapl),
    "Treynor": treynor_ratio(aapl, sp500),
    "Information Ratio": information_ratio(aapl, sp500),
    "Calmar": calmar_ratio(aapl)
}

df_metrics = pd.DataFrame(metrics, index=["AAPL"])
print("\n=== MÉTRICAS DE DESEMPEÑO ===")
print(df_metrics.round(3))