# -*- coding: utf-8 -*-
"""Clase_CAPM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xq3qY70vPdCAgRtxndThmWgMubUqjt69
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

# Descargar datos mensuales
aapl = yf.download("AAPL", start="2000-02-01", end="2016-01-31", interval="1mo")['Close']
sp500 = yf.download("^GSPC", start="2000-02-01", end="2016-01-31", interval="1mo")['Close']

# Asegurar que sean Series planas (quitar el MultiIndex)
if isinstance(aapl, pd.DataFrame):
    aapl = aapl['AAPL']
if isinstance(sp500, pd.DataFrame):
    sp500 = sp500['^GSPC']

# Calcular retornos
returns = pd.DataFrame({
    'AAPL': aapl.pct_change(),
    'SP500': sp500.pct_change()
}).dropna()

# Gráfico
plt.scatter(returns['SP500'], returns['AAPL'], alpha=0.6, label="Datos mensuales")

plt.title("Relación AAPL vs S&P500")
plt.xlabel("Retornos S&P500")
plt.ylabel("Retornos AAPL")
plt.legend()
plt.show()

# Regresión CAPM
X = returns['SP500'].values.reshape(-1, 1)
y = returns['AAPL'].values
reg = LinearRegression().fit(X, y)

beta = reg.coef_[0]
alpha = reg.intercept_

print(f"Alpha: {alpha:.4f}, Beta: {beta:.4f}")
# Gráfico
plt.scatter(returns['SP500'], returns['AAPL'], alpha=0.6, label="Datos mensuales")
plt.plot(returns['SP500'], reg.predict(X), color='red', label="Línea CAPM")
plt.title("Relación AAPL vs S&P500")
plt.xlabel("Retornos S&P500")
plt.ylabel("Retornos AAPL")
plt.legend()
plt.show()

beta = reg.coef_[0]
alpha = reg.intercept_
print(f"Alpha: {alpha:.4f}, Beta: {beta:.4f}")

# Filtrar solo puntos positivos
returns_pos = returns[(returns['SP500'] > 0) & (returns['AAPL'] > 0)]

# Línea de regresión (solo hasta 0.5 en X)
X_line = np.linspace(0, 0.5, 100).reshape(-1, 1)
y_line = reg.predict(X_line)

# Limitar la línea de regresión al rango visible (Y <= 0.5)
mask = (y_line >= 0) & (y_line <= 0.5)
X_line = X_line[mask]
y_line = y_line[mask]

# Gráfico
plt.figure(figsize=(7, 7))
plt.scatter(returns_pos['SP500'], returns_pos['AAPL'], alpha=0.6, label="Datos positivos")
plt.plot(X_line, y_line, color='red', label="Línea CAPM")

# Ejes: de 0 a 0.5 con pasos de 0.05
plt.xlim(0, 0.5)
plt.ylim(0, 0.5)
plt.xticks(np.arange(0, 0.55, 0.05))
plt.yticks(np.arange(0, 0.55, 0.05))
plt.axis('scaled')

# Estilo
plt.title("Relación AAPL vs S&P500")
plt.xlabel("Retornos S&P500")
plt.ylabel("Retornos AAPL")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()