# -*- coding: utf-8 -*-
"""Cova.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVf0jxp5ds6paIbRrJCJyrT9_tZ7nBcS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sf_library as sfl

# sectores = [
#     'XLK', 'VGT', 'IYW',  # Tecnología
#     'XLF', 'VFH', 'IYF',  # Finanzas
#     'XLV', 'VHT', 'IYH',  # Salud
#     'XLP', 'VDC', 'IYK',  # Consumo básico
#     'XLY', 'VCR', 'IYC',  # Consumo discrecional
#     'XLE', 'VDE', 'IYE',  # Energía
#     'XLI', 'VIS', 'IYJ',  # Industrial
#     'XLC', 'VOX', 'IYZ',  # Comunicaciones
#     'XLB', 'VAW', 'IYM',  # Materiales
#     'XLU', 'VPU', 'IDU',  # Servicios públicos
#     'XLRE', 'VNQ', 'IYR'  # Bienes raíces
# ]

# monedas = [
#     'USD',  # Dólar estadounidense
#     'GBP',  # Libra esterlina
#     'CAD',  # Dólar canadiense
#     'CHF',  # Franco suizo
#     'NZD',  # Dólar neozelandés
#     'CNY',  # Yuan chino
#     'MXN'   # Peso mexicano
# ]
index = [
    'SPY',  # S&P 500
    'QQQ',  # Nasdaq 100
]

sfl.descargar_tickers(index, carpeta='MarketData', start='2000-01-01',end = '2024-01-01')

data = sfl.daily_return('VAW', data_dir="MarketData")
data

"""# 🌐 ¿Cómo hacer una matriz de correlaciones?

Todos los returns juntos
"""

# tickers = [
#     'XLK', # Tecnología
#     'XLF', # Finanzas
#     'XLV', # Salud
#     'XLP', # Consumo básico
#     'XLY', # Consumo discrecional
#     'XLE', # Energía
#     'XLI', # Industrial
#     'XLC', # Comunicaciones
#     'XLB', # Materiales
#     'XLU', # Servicios públicos
#     'XLRE',# Bienes raíces
# ]
tickers = [
    'XLK', 'VGT', 'IYW',  # Tecnología
    'XLF', 'VFH', 'IYF',  # Finanzas
    'XLV', 'VHT', 'IYH',  # Salud
    'XLP', 'VDC', 'IYK',  # Consumo básico
    'XLY', 'VCR', 'IYC',  # Consumo discrecional
    'XLE', 'VDE', 'IYE',  # Energía
    'XLI', 'VIS', 'IYJ',  # Industrial
    'XLC', 'VOX', 'IYZ',  # Comunicaciones
    'XLB', 'VAW', 'IYM',  # Materiales
    'XLU', 'VPU', 'IDU',  # Servicios públicos
    'XLRE', 'VNQ', 'IYR'  # Bienes raíces
]


all_returns = []

for ticker in tickers:
    t = sfl.daily_return(ticker, data_dir="MarketData")
    t = t[['date', 'return']].rename(columns={'return': ticker})
    all_returns.append(t)


df = all_returns[0]
for t in all_returns[1:]:
    df = pd.merge(df, t, on='date', how='inner')

df = df.dropna().sort_values('date').reset_index(drop=True)
# df = df[(df['date']<'2021-01-01')&(df['date']>'2019-01-01')]
df = df[df['date']<'2019-01-01']
df

returns_only = df.drop(columns='date')
mtx_var_covar = returns_only.cov().values
mtx_correl = returns_only.corr().values

print("Primeras filas del DataFrame sincronizado:")
print(df.head(), "\n")

print("Matriz Varianza-Covarianza:")
print(mtx_var_covar, "\n")

print("Matriz de Correlaciones:")
print(mtx_correl)

mtx_correl = returns_only.corr()


plt.figure(figsize=(18, 16))
sns.heatmap(
    mtx_correl,
    annot=True,        # imprime el valor de correlación en cada celda
    fmt=".2f",         # 2 decimales
    cmap="coolwarm",
    vmin=0, vmax=1
)
plt.title("Matriz de Correlaciones de Tickers")
plt.tight_layout()
plt.show()